baseURL = "https://gbak.space/"
languageCode = "ru"
title = "GBAK"
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 8

[permalinks]
  articles = "/articles/:slug/"

[params]
  description = "Экспертные публикации по процессному подходу, операционной эффективности и бизнес-анализу."

canonifyURLs = false
relativeURLs = false
enableRobotsTXT = true